spring:
  application:
    name: bofit
  profiles:
    group:
      local: local-db, local-port, common
      dev-blue: common, dev-db, dev-blue-port
      dev-green: common, dev-db, dev-green-port
      prod: prod-db, prod-port, common
    active: local

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
kakao:
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
server:
  forward-headers-strategy: FRAMEWORK


---
spring:
  config:
    activate:
      on-profile: local-db
  jpa:
    hibernate:
      ddl-auto: ${LOCAL_DATASOURCE_DDL_AUTO}
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${LOCAL_REDIRECT_URI}
---
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-db
  jpa:
    hibernate:
      ddl-auto: ${DEV_DATASOURCE_DDL_AUTO}
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${PROD_REDIRECT_URI}

---
spring:
  config:
    activate:
      on-profile: dev-port
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev-blue-port
server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: dev-green-port
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod-db
  jpa:
    hibernate:
      ddl-auto: ${PROD_DATASOURCE_DDL_AUTO}
  datasource:
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 8082