package org.sopt.bofit.domain.insurancereport.constant;

import javax.swing.plaf.PanelUI;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/**
 * POINT_: 보장 시 점수
 * VALID_COVERAGE_: 유효한 보장 금액
 * MEDICAL_HISTORY_: 질병력
 *
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class InsuranceReportFactorConstant {

	public static final int MAJOR_DISEASE_CONSIDER_AGE = 50;
	public static final int POINT_MAJOR_DISEASE_OVER_CONSIDER_AGE = 5;

	public static final int VALID_COVERAGE_GENERAL_CANCER_DIAGNOSIS = 5000;
	public static final int VALID_COVERAGE_CEREBRAL_HEMORRHAGE_DIAGNOSIS = 2000;
	public static final int VALID_COVERAGE_ISCHEMIC_HEART_DISEASE_DIAGNOSIS = 2000;
	public static final int POINT_ATYPICAL_CANCER = 3;
	public static final int POINT_JOB_INJURY = 3;

	public static final int POINT_IS_MARRIED_DEATH = 3;
	public static final int POINT_HAS_CHILD_DEATH = 5;
	public static final int POINT_IS_DRIVER_INJURY = 1;

	// 질병력
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_GENERAL_CANCER_DIAGNOSIS = 5000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_GENERAL_CANCER_SURGERY = 1000;
	public static final int POINT_MEDICAL_HISTORY_GENERAL_CANCER = 10;

	public static final int VALID_COVERAGE_MEDICAL_HISTORY_CEREBRAL_HEMORRHAGE_DIAGNOSIS = 2000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_CEREBRAL_HEMORRHAGE_SURGERY = 1000;
	public static final int POINT_MEDICAL_HISTORY_CEREBRAL_HEMORRHAGE = 10;

	public static final int VALID_COVERAGE_MEDICAL_HISTORY_ISCHEMIC_HEART_DISEASE_DIAGNOSIS = 2000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_ISCHEMIC_HEART_DISEASE_SURGERY = 1000;
	public static final int POINT_MEDICAL_HISTORY_ISCHEMIC_HEART_DISEASE = 10;
	public static final int POINT_MEDICAL_HISTORY_HEART_DISEASE_ELSE_ISCHEMIC = 5;

	// 질병력 - 호흡기
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RESPIRATORY_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_MEDICAL_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE = 7;
	public static final int POINT_MEDICAL_HISTORY_RESPIRATORY_DISEASE_DISABILITY_GE_3_PCT = 7;
	public static final int POINT_MEDICAL_HISTORY_RESPIRATORY_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_MEDICAL_HISTORY_RESPIRATORY_DAILY_HOSPITALIZATION_DISEASE = 3;


	// 질병력 - 간
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RIVER_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RIVER_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RIVER_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_RIVER_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_MEDICAL_HISTORY_RIVER_DISEASE_SURGERY_TYPE = 7;
	public static final int POINT_MEDICAL_HISTORY_RIVER_DISEASE_DISABILITY_GE_3_PCT = 7;
	public static final int POINT_MEDICAL_HISTORY_RIVER_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_MEDICAL_HISTORY_RIVER_DAILY_HOSPITALIZATION_DISEASE = 3;


	// 질병력 - 신장
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_MEDICAL_HISTORY_KIDNEY_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_MEDICAL_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE = 7;
	public static final int POINT_MEDICAL_HISTORY_KIDNEY_DISEASE_DISABILITY_GE_3_PCT = 7;
	public static final int POINT_MEDICAL_HISTORY_KIDNEY_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_MEDICAL_HISTORY_KIDNEY_DAILY_HOSPITALIZATION_DISEASE = 3;


	//질병력 - 정신
	public static final int POINT_MEDICAL_HISTORY_MENTAL_DAILY_HOSPITALIZATION_DISEASE = 3;
	//질병력 - 만성
	public static final int POINT_MEDICAL_HISTORY_CHRONIC_DAILY_HOSPITALIZATION_DISEASE = 3;


	//가족력  - 암
	public static final int VALID_COVERAGE_FAMILY_HISTORY_GENERAL_CANCER_DIAGNOSIS = 5000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_GENERAL_CANCER_SURGERY = 1000;
	public static final int POINT_FAMILY_HISTORY_GENERAL_CANCER_DIAGNOSIS = 5;
	public static final int POINT_FAMILY_HISTORY_GENERAL_CANCER_SURGERY = 5;

	//가족력  - 뇌혈관
	public static final int VALID_COVERAGE_FAMILY_HISTORY_CEREBRAL_HEMORRHAGE_DIAGNOSIS = 2000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_CEREBRAL_HEMORRHAGE_SURGERY = 1000;
	public static final int POINT_FAMILY_HISTORY_CEREBRAL_HEMORRHAGE_DIAGNOSIS = 5;
	public static final int POINT_FAMILY_HISTORY_CEREBRAL_HEMORRHAGE_SURGERY = 5;

	//가족력 - 심장
	public static final int VALID_COVERAGE_FAMILY_HISTORY_ISCHEMIC_HEART_DISEASE_DIAGNOSIS = 2000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_ISCHEMIC_HEART_DISEASE_SURGERY = 1000;
	public static final int POINT_FAMILY_HISTORY_ISCHEMIC_HEART_DISEASE_DIAGNOSIS = 5;
	public static final int POINT_FAMILY_HISTORY_ISCHEMIC_HEART_DISEASE_SURGERY = 5;

	public static final int POINT_FAMILY_HISTORY_EXTENDED_HEART_DISEASE_DIAGNOSIS = 3;
	public static final int POINT_FAMILY_HISTORY_EXTENDED_HEART_DISEASE_SURGERY = 3;


	// 가족력 - 호흡기
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RESPIRATORY_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_FAMILY_HISTORY_RESPIRATORY_DISEASE_SURGERY_TYPE = 5;
	public static final int POINT_FAMILY_HISTORY_RESPIRATORY_DISEASE_DISABILITY_GE_3_PCT = 5;
	public static final int POINT_FAMILY_HISTORY_RESPIRATORY_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_FAMILY_HISTORY_RESPIRATORY_DAILY_HOSPITALIZATION_DISEASE = 3;


	// 가족력 - 간
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RIVER_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RIVER_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RIVER_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_RIVER_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_FAMILY_HISTORY_RIVER_DISEASE_SURGERY_TYPE = 5;
	public static final int POINT_FAMILY_HISTORY_RIVER_DISEASE_DISABILITY_GE_3_PCT = 5;
	public static final int POINT_FAMILY_HISTORY_RIVER_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_FAMILY_HISTORY_RIVER_DAILY_HOSPITALIZATION_DISEASE = 3;


	// 가족력 - 신장
	public static final int VALID_COVERAGE_FAMILY_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_3 = 100;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_4 = 500;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE_5 = 1000;
	public static final int VALID_COVERAGE_FAMILY_HISTORY_KIDNEY_DISEASE_DISABILITY_GE_3_PCT = 3000;


	public static final int POINT_FAMILY_HISTORY_KIDNEY_DISEASE_SURGERY_TYPE = 5;
	public static final int POINT_FAMILY_HISTORY_KIDNEY_DISEASE_DISABILITY_GE_3_PCT = 5;
	public static final int POINT_FAMILY_HISTORY_KIDNEY_DISEASE_SURGERY_AND_DISEASE_SURGERY_TYPE = 3;
	public static final int POINT_FAMILY_HISTORY_KIDNEY_DAILY_HOSPITALIZATION_DISEASE = 3;


	// 가족력 - 정신
	public static final int POINT_FAMILY_HISTORY_MENTAL_DISEASE_SURGERY_TYPE = 7;
	public static final int POINT_FAMILY_HISTORY_CHRONIC_DISEASE_SURGERY_TYPE = 7;


	//질병력 - 정신
	public static final int POINT_FAMILY_HISTORY_MENTAL_DAILY_HOSPITALIZATION_DISEASE = 1;
	//질병력 - 만성
	public static final int POINT_FAMILY_HISTORY_CHRONIC_DAILY_HOSPITALIZATION_DISEASE = 1;


	// 보장 상황 - 1 - REQUEST 를 붙이는 게
	// public static final int POINT_COVERAGE_SELECT_FAMILY_HISTORY_CHRONIC_DAILY_HOSPITALIZATION_DISEASE = 1;

	public static final int VALID_COVERAGE_MAJOR_DISEASE_GENERAL_CANCER_DIAGNOSIS = 5000;
	public static final int VALID_COVERAGE_MAJOR_DISEASE_GENERAL_CANCER_SURGERY = 1000;
	public static final int POINT_MAJOR_DISEASE_GENERAL_CANCER_DIAGNOSIS = 10;
	public static final int PONT_MAJOR_DISEASE_GENERAL_CANCER_SURGERY = 10;

	// 보장 상황 - 2
	public static final int VALID_COVERAGE_SURGERY_COVERAGE




}
